# Generated by Django 3.1.7 on 2021-06-24 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default='', max_length=50, null=True)),
                ('descripcion', models.TextField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50, null=True)),
                ('propietario', models.TextField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(default='', max_length=50, null=True)),
                ('fecha', models.DateField(default='', max_length=50, null=True)),
                ('producto', models.ForeignKey(default='', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.AddField(
            model_name='producto',
            name='puesto',
            field=models.ForeignKey(default='', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.puesto'),
        ),
    ]
